# Explorando algunas caracteristicas de Scipy

 <img src="https://media.licdn.com/dms/image/v2/D4D12AQELmHDR85Un1Q/article-cover_image-shrink_600_2000/article-cover_image-shrink_600_2000/0/1683096619215?e=2147483647&v=beta&t=YdjkdiEFLFimO6oaSxjWeyHY488VuiM__K0OeH1vHbs" alt="Logo de scipy" width="400">



In [2]:
# importando numpy
import numpy as np

In [3]:
# 1. Creación de arrays
print("1. Creación de arrays:")
arr_1d = np.array([1, 2, 3, 4, 5])  # Array unidimensional
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])  # Array bidimensional
print("Array 1D:", arr_1d)
print("Array 2D:")
print(arr_2d)
print("\n")

1. Creación de arrays:
Array 1D: [1 2 3 4 5]
Array 2D:
[[1 2 3]
 [4 5 6]]




In [4]:
# 2. Operaciones aritméticas
print("2. Operaciones aritméticas (con arrays):")
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

sum_arr = arr_1d + 10  # Sumar un escalar
print("Array 1D + 10:", sum_arr)

arr_mul = arr_1d * 2  # Multiplicar por un escalar
print("Array 1D * 2:", arr_mul)

arr_dot = np.dot(arr_2d, arr_2d.T)  # Producto punto
print("Producto punto de arr_2d y su transpuesta:")
print(arr_dot)
print("\n")

2. Operaciones aritméticas (con arrays):
Array 1D + 10: [11 12 13 14 15]
Array 1D * 2: [ 2  4  6  8 10]
Producto punto de arr_2d y su transpuesta:
[[14 32]
 [32 77]]




In [5]:
# 3. Funciones estadísticas
print("3. Funciones estadísticas:")
arr_random = np.random.rand(10)  # Array con valores aleatorios entre 0 y 1
print("Array de valores aleatorios:", arr_random)

print("Promedio de arr_random:", np.mean(arr_random))
print("Desviación estándar de arr_random:", np.std(arr_random))
print("Máximo de arr_random:", np.max(arr_random))
print("Mínimo de arr_random:", np.min(arr_random))
print("\n")

3. Funciones estadísticas:
Array de valores aleatorios: [0.42918608 0.18153139 0.78260044 0.08136527 0.09299774 0.52273134
 0.50157647 0.468119   0.58022114 0.13800448]
Promedio de arr_random: 0.37783333275109005
Desviación estándar de arr_random: 0.22736987530485198
Máximo de arr_random: 0.7826004403846987
Mínimo de arr_random: 0.0813652653663266


